apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-bora-lite
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-bora-lite
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-bora-lite
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: wait-for-mantis
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for mantis pod to be ready..."
            while ! kubectl get pods -l app.kubernetes.io/name={{ include "sublime-rules-engine.name" . }}-mantis -o jsonpath='{.items[0].metadata.name}' > /dev/null 2>&1; do
              echo "Mantis pod not found yet, waiting..."
              sleep 5
            done
            MANTIS_POD_NAME=$(kubectl get pods -l app.kubernetes.io/name={{ include "sublime-rules-engine.name" . }}-mantis -o jsonpath='{.items[0].metadata.name}')
            echo "Mantis pod found: $MANTIS_POD_NAME. Waiting for migrations to complete..."
            until kubectl logs $MANTIS_POD_NAME | grep -q "Non-blocking migrations are up to date"; do
              echo "Migrations not complete yet, waiting..."
              sleep 5
            done
            echo "Mantis migrations are complete. Starting bora-lite."
      containers:
      - name: bora-lite
        image: "{{ .Values.image.bora_lite }}"
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ include "sublime-rules-engine.fullname" . }}
        env:
        - name: POSTGRES_HOST
          value: {{ include "sublime-rules-engine.fullname" . }}-postgres
        - name: DB_RUN_MIGRATIONS
          value: "false"
        - name: PERSISTENT_STORAGE
          value: "/data"
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "sublime-rules-engine.fullname" . }}-persistent-storage 