apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-mantis
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sublime-rules-engine.fullname" . }}-mantis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-mantis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-mantis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mantis
          image: "{{ .Values.image.mantis }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: {{ include "sublime-rules-engine.fullname" . }}
          env:
            - name: POSTGRES_HOST
              value: {{ include "sublime-rules-engine.fullname" . }}-postgres
            - name: S3_HOST
              value: {{ include "sublime-rules-engine.fullname" . }}-s3
            - name: S3_BUCKET
              value: email-screenshots
            - name: STRELKA_HOST
              value: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
            - name: HYDRA_HOST
              value: {{ include "sublime-rules-engine.fullname" . }}-hydra
            - name: PERSISTENT_STORAGE
              value: /data
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-mantis
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-mantis
    app.kubernetes.io/instance: {{ .Release.Name }} 