apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-persistent-storage
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path 