apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-pod-reader
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-read-pods
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sublime-rules-engine.fullname" . }}-pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }} 