apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-redis
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.redis }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-redis
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }} 