apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-yara-rules
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
data:
  hello_world.yara: |-
{{ .Files.Get "rules/hello_world.yara" | indent 4 }} 