apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password }}
  SUBLIME_SECRET_KEY: {{ .Values.sublime.secretKey }}
  JWT_SECRET: {{ .Values.sublime.jwtSecret }}
  POSTGRES_ENCRYPTION_KEY: {{ .Values.sublime.postgresEncryptionKey }}
  S3_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey }}
  POSTGRES_USER: {{ .Values.postgresql.username }}
  POSTGRES_DB: {{ .Values.postgresql.database }}
  REDIS_HOST: '{{ include "sublime-rules-engine.fullname" . }}-redis' 