apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
data:
  client.yaml: |
    client:
      gatekeeper:
        host: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
        port: 56564
  logging.yaml: |
    version: 1
    disable_existing_loggers: False
    formatters:
      default:
        format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
    root:
      handlers:
        - console
      level: DEBUG
  settings.yaml: |
    limits:
      scan: 1200
      depth: 10
    responses:
      stale: 600
    timeout:
      scan: 600
      server: 1800
  strelka.yaml: |
    # Strelka configuration file
    # Updated: 2022-09-02
    server:
      # Location of logging configuration file
      # Default: /etc/strelka/logging.yaml
      log: /etc/strelka/logging.yaml

      # Location of settings configuration file
      # Default: /etc/strelka/settings.yaml
      settings: /etc/strelka/settings.yaml

    backend:
      # Location of scanner configuration files
      # Default: /etc/strelka/scanners/
      scanners: /etc/strelka/scanners/

      # Location of taste files
      # Default: /etc/strelka/tastes/
      tastes: /etc/strelka/tastes/

      # Location of Yara rule files
      # Default: /etc/strelka/yara/
      yara: /etc/strelka/yara/
  scan_yara.yaml: |
    scanners:
      ScanYara:
        enabled: True
  tastes.yaml: |
    tastes:
      - mime:
          - text/plain
        scanners:
          - ScanYara
  backend.yaml: |
    version: 1
    logging_cfg: /etc/strelka/logging.yaml
    
    limits:
      max_files: 5000
      time_to_live: 900
      max_depth: 10
      distribution: 1200
      scanner: 150
    
    coordinator:
      addr: '{{ include "sublime-rules-engine.fullname" . }}-redis:{{ .Values.redis.port }}'
      db: 0
    
    tasting:
      yara_rules: /etc/strelka/yara/
    
    scanners:
      - flavor: "*"
        scanner: ScanYara
        priority: 5
  manager.yaml: |
    coordinator:
      addr: '{{ include "sublime-rules-engine.fullname" . }}-redis:{{ .Values.redis.port }}'
      db: 0
      pool: 100
      read: 10s
  frontend.yaml: |
    version: 1
    logging_cfg: /etc/strelka/logging.yaml
    
    server: "0.0.0.0:56564"
    
    coordinator:
      addr: '{{ include "sublime-rules-engine.fullname" . }}-redis:{{ .Values.redis.port }}'
      db: 0
      pool: 100
      read: 10s
    
    response:
      timeout: 60
      log: /dev/stdout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-backend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.strelka.backendReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-backend
        image: "{{ .Values.image.strelka_backend }}"
        command: ["strelka-backend", "--worker-config", "/etc/strelka/backend.yaml"]
        envFrom:
        - secretRef:
            name: {{ include "sublime-rules-engine.fullname" . }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
        - name: yara-rules
          mountPath: /etc/strelka/yara
        - name: scanners-config
          mountPath: /etc/strelka/scanners
        - name: tastes-config
          mountPath: /etc/strelka/tastes
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
      - name: yara-rules
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-yara-rules
      - name: scanners-config
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
          items:
          - key: scan_yara.yaml
            path: scan_yara.yaml
      - name: tastes-config
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
          items:
          - key: tastes.yaml
            path: tastes.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-frontend
        image: "{{ .Values.image.strelka_frontend }}"
        command: ["strelka-frontend", "/etc/strelka/frontend.yaml"]
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend
          containerPort: 56564
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
        - name: yara-rules
          mountPath: /etc/strelka/yara
        - name: scanners-config
          mountPath: /etc/strelka/scanners
        - name: tastes-config
          mountPath: /etc/strelka/tastes
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
      - name: yara-rules
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-yara-rules
      - name: scanners-config
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
          items:
          - key: scan_yara.yaml
            path: scan_yara.yaml
      - name: tastes-config
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
          items:
          - key: tastes.yaml
            path: tastes.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 56564
    targetPort: frontend
    protocol: TCP
    name: frontend
  selector:
    app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-manager
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-manager
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-manager
        image: "{{ .Values.image.strelka_manager }}"
        command: ["strelka-manager", "/etc/strelka/manager.yaml"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config 