apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
data:
  client.yaml: |
    client:
      gatekeeper:
        host: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
        port: 56564
  logging.yaml: |
    version: 1
    disable_existing_loggers: False
    formatters:
      default:
        format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: default
        level: INFO
    root:
      handlers:
        - console
      level: INFO
  settings.yaml: |
    limits:
      scan: 1200
      depth: 10
    responses:
      stale: 600
    timeout:
      scan: 600
      server: 1800
  strelka.yaml: |
    # Strelka configuration file
    # Updated: 2022-09-02
    server:
      # Location of logging configuration file
      # Default: /etc/strelka/logging.yaml
      log: /etc/strelka/logging.yaml

      # Location of settings configuration file
      # Default: /etc/strelka/settings.yaml
      settings: /etc/strelka/settings.yaml

    backend:
      # Location of scanner configuration files
      # Default: /etc/strelka/scanners/
      scanners: /etc/strelka/scanners/

      # Location of taste files
      # Default: /etc/strelka/tastes/
      tastes: /etc/strelka/tastes/

      # Location of Yara rule files
      # Default: /etc/strelka/yara/
      yara: /etc/strelka/yara/
  manager.yaml: |
    coordinator:
      addr: '{{ include "sublime-rules-engine.fullname" . }}-redis:{{ .Values.redis.port }}'
      db: 0
      pool: 100
      read: 10s
  frontend.yaml: |
    server: "0.0.0.0:56564"
    coordinator:
      addr: '{{ include "sublime-rules-engine.fullname" . }}-redis:{{ .Values.redis.port }}'
      db: 0
      pool: 100
      read: 10s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-backend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.strelka.backendReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-backend
        image: "{{ .Values.image.strelka_backend }}"
        command: ["sleep", "infinity"]
        envFrom:
        - secretRef:
            name: {{ include "sublime-rules-engine.fullname" . }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
        - name: yara-volume
          mountPath: /etc/strelka/yara
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
      - name: yara-volume
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-frontend
        image: "{{ .Values.image.strelka_frontend }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: frontend
          containerPort: 56564
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-frontend
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 56564
    targetPort: frontend
    protocol: TCP
    name: frontend
  selector:
    app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-strelka-manager
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-manager
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sublime-rules-engine.name" . }}-strelka-manager
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: strelka-manager
        image: "{{ .Values.image.strelka_manager }}"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/strelka
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "sublime-rules-engine.fullname" . }}-strelka-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sublime-rules-engine.fullname" . }}-persistent-storage
  labels:
    {{- include "sublime-rules-engine.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path 